// generated by go generate; DO NOT EDIT.
package cursorfont

import "github.com/jezek/xgb/xproto"

const (
	XC_num_glyphs          = 154
	XC_X_cursor            = 0
	XC_arrow               = 2
	XC_based_arrow_down    = 4
	XC_based_arrow_up      = 6
	XC_boat                = 8
	XC_bogosity            = 10
	XC_bottom_left_corner  = 12
	XC_bottom_right_corner = 14
	XC_bottom_side         = 16
	XC_bottom_tee          = 18
	XC_box_spiral          = 20
	XC_center_ptr          = 22
	XC_circle              = 24
	XC_clock               = 26
	XC_coffee_mug          = 28
	XC_cross               = 30
	XC_cross_reverse       = 32
	XC_crosshair           = 34
	XC_diamond_cross       = 36
	XC_dot                 = 38
	XC_dotbox              = 40
	XC_double_arrow        = 42
	XC_draft_large         = 44
	XC_draft_small         = 46
	XC_draped_box          = 48
	XC_exchange            = 50
	XC_fleur               = 52
	XC_gobbler             = 54
	XC_gumby               = 56
	XC_hand1               = 58
	XC_hand2               = 60
	XC_heart               = 62
	XC_icon                = 64
	XC_iron_cross          = 66
	XC_left_ptr            = 68
	XC_left_side           = 70
	XC_left_tee            = 72
	XC_leftbutton          = 74
	XC_ll_angle            = 76
	XC_lr_angle            = 78
	XC_man                 = 80
	XC_middlebutton        = 82
	XC_mouse               = 84
	XC_pencil              = 86
	XC_pirate              = 88
	XC_plus                = 90
	XC_question_arrow      = 92
	XC_right_ptr           = 94
	XC_right_side          = 96
	XC_right_tee           = 98
	XC_rightbutton         = 100
	XC_rtl_logo            = 102
	XC_sailboat            = 104
	XC_sb_down_arrow       = 106
	XC_sb_h_double_arrow   = 108
	XC_sb_left_arrow       = 110
	XC_sb_right_arrow      = 112
	XC_sb_up_arrow         = 114
	XC_sb_v_double_arrow   = 116
	XC_shuttle             = 118
	XC_sizing              = 120
	XC_spider              = 122
	XC_spraycan            = 124
	XC_star                = 126
	XC_target              = 128
	XC_tcross              = 130
	XC_top_left_arrow      = 132
	XC_top_left_corner     = 134
	XC_top_right_corner    = 136
	XC_top_side            = 138
	XC_top_tee             = 140
	XC_trek                = 142
	XC_ul_angle            = 144
	XC_umbrella            = 146
	XC_ur_angle            = 148
	XC_watch               = 150
	XC_xterm               = 152
)

var String2CursorMap = map[string]xproto.Cursor{
	"XC_num_glyphs":          0x9a,
	"XC_X_cursor":            0x0,
	"XC_arrow":               0x2,
	"XC_based_arrow_down":    0x4,
	"XC_based_arrow_up":      0x6,
	"XC_boat":                0x8,
	"XC_bogosity":            0xa,
	"XC_bottom_left_corner":  0xc,
	"XC_bottom_right_corner": 0xe,
	"XC_bottom_side":         0x10,
	"XC_bottom_tee":          0x12,
	"XC_box_spiral":          0x14,
	"XC_center_ptr":          0x16,
	"XC_circle":              0x18,
	"XC_clock":               0x1a,
	"XC_coffee_mug":          0x1c,
	"XC_cross":               0x1e,
	"XC_cross_reverse":       0x20,
	"XC_crosshair":           0x22,
	"XC_diamond_cross":       0x24,
	"XC_dot":                 0x26,
	"XC_dotbox":              0x28,
	"XC_double_arrow":        0x2a,
	"XC_draft_large":         0x2c,
	"XC_draft_small":         0x2e,
	"XC_draped_box":          0x30,
	"XC_exchange":            0x32,
	"XC_fleur":               0x34,
	"XC_gobbler":             0x36,
	"XC_gumby":               0x38,
	"XC_hand1":               0x3a,
	"XC_hand2":               0x3c,
	"XC_heart":               0x3e,
	"XC_icon":                0x40,
	"XC_iron_cross":          0x42,
	"XC_left_ptr":            0x44,
	"XC_left_side":           0x46,
	"XC_left_tee":            0x48,
	"XC_leftbutton":          0x4a,
	"XC_ll_angle":            0x4c,
	"XC_lr_angle":            0x4e,
	"XC_man":                 0x50,
	"XC_middlebutton":        0x52,
	"XC_mouse":               0x54,
	"XC_pencil":              0x56,
	"XC_pirate":              0x58,
	"XC_plus":                0x5a,
	"XC_question_arrow":      0x5c,
	"XC_right_ptr":           0x5e,
	"XC_right_side":          0x60,
	"XC_right_tee":           0x62,
	"XC_rightbutton":         0x64,
	"XC_rtl_logo":            0x66,
	"XC_sailboat":            0x68,
	"XC_sb_down_arrow":       0x6a,
	"XC_sb_h_double_arrow":   0x6c,
	"XC_sb_left_arrow":       0x6e,
	"XC_sb_right_arrow":      0x70,
	"XC_sb_up_arrow":         0x72,
	"XC_sb_v_double_arrow":   0x74,
	"XC_shuttle":             0x76,
	"XC_sizing":              0x78,
	"XC_spider":              0x7a,
	"XC_spraycan":            0x7c,
	"XC_star":                0x7e,
	"XC_target":              0x80,
	"XC_tcross":              0x82,
	"XC_top_left_arrow":      0x84,
	"XC_top_left_corner":     0x86,
	"XC_top_right_corner":    0x88,
	"XC_top_side":            0x8a,
	"XC_top_tee":             0x8c,
	"XC_trek":                0x8e,
	"XC_ul_angle":            0x90,
	"XC_umbrella":            0x92,
	"XC_ur_angle":            0x94,
	"XC_watch":               0x96,
	"XC_xterm":               0x98,
}
